### ISSUE TITLE
Noteskins in the Options menu

### ISSUE THREAD

**Issue by SteveeWasTaken** [Gui-iago/FNF-BedrockEngine#1]
### What feature do you want to get added on the **base** engine?

There could be an option to change Noteskins in the Options Menu, under the "Judgements" setting. It's something pretty small but I think it'd be really cool.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, and 5K+

**Comment by Gui-iago** [comment]
with my current knowledge on coding, this won't be possible (for now), unless someone makes a pull request, or I manage to add it myself

**Comment by Luisinhi010** [comment]
I first need the note asstes but then i will add notes skins

**Comment by Stilic** [comment]
wait i can do it lmao

**Comment by Gui-iago** [comment]
> wait i can do it lmao

it's open to pr :pog:

**Comment by Gui-iago** [comment]
already planned, so I closed it
