### ISSUE TITLE
Why is Rate Mod commented out in the GameplayChangers substate?

### ISSUE THREAD

**Issue by prokube** [Gui-iago/FNF-BedrockEngine#10]
### What is your question?

idk it's pretty easy to implement. unless you want an option for disabling pitch change with speed

**Comment by Gui-iago** [comment]
that's from Psych Engine, Speed Modifiers aren't properly implemented on Psych Engine yet, and while I could implement it, I don't have the knowledge to do so, however...

**Comment by prokube** [comment]
> I don't have the knowledge to do so, however...

Check out the functions for [Lime's Audio Library (whatever AL stands for)](https://api.haxeflixel.com/lime/media/openal/AL.html) I guess. I think there's some pitch stuff in there somewhere

**Comment by Gui-iago** [comment]
planned, so I will close this for now

**Comment by prokube** [comment]
cool :+1:
