### ISSUE TITLE
Use Github Projects to kinda show where stuff is in the coding process

### ISSUE THREAD

**Issue by prokube** [Gui-iago/FNF-BedrockEngine#12]
### What needs to be documented?

Like a "Back burner, Planned, In Progress, Done" thingy with features that we know you've considered / are Enhancement issues (this is made easier by using GITHUB's projects because you can make cards from issues or PRs)

##### the enhancement form says "added to base engine" and this isn't an engine thing so i used this one instead :l

**Comment by Stilic** [comment]
Just opened one @Gui-iago.
