### ISSUE TITLE
uhhhhhhhhh help 

### ISSUE THREAD

**Issue by Razthefunni** [Gui-iago/FNF-BedrockEngine#20]
### Describe your bug here.

i dont know exactly what it means by characters 4-12 i dont really know where to put "]" 
![image](https://user-images.githubusercontent.com/98192860/152223784-3d43db8c-fd59-4e5e-870d-f56881e3f0b6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt edit anything as soon as i downloaded  it and build it it said the error that i send

**Comment by Razthefunni** [comment]
i dont know if im dumb for not knowing this but im a bit new to coding so yeah im kinda stupid with this

**Comment by Gui-iago** [comment]
fixed

**Comment by Gui-iago** [comment]
update the source

**Comment by Razthefunni** [comment]
OH SHIT i forgor to mention visual and ui crashes as well if i hit it

**Comment by Gui-iago** [comment]
> OH SHIT i forgor to mention visual and ui crashes as well if i hit the option

gonna go check it
