### ISSUE TITLE
Object doesn't have propetry "x"

### ISSUE THREAD

**Issue by SonicProYT** [Gui-iago/FNF-BedrockEngine#5]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/62410083/150447675-e046705f-11f6-435f-98f1-a0baa790539a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only the sprites and stuff

**Comment by Gui-iago** [comment]
what exactly did you try to do here?

**Comment by SonicProYT** [comment]
i was trying to test the engine

**Comment by Gui-iago** [comment]
> i was trying to test the engine

fixed, download the latest dev build
